export type ApiErrorCode = 
  | 'FORBIDDEN'
  | 'DATABASE_ERROR'
  | 'INTERNAL_ERROR'
  | 'VALIDATION_ERROR'
  | 'FETCH_ERROR'
  | 'UPDATE_ERROR'
  | 'CREATE_ERROR'
  | 'DELETE_ERROR'
  | 'NOT_FOUND'
  | 'MISSING_ID'
  | 'MISSING_PARAMETERS'
  | 'INVALID_ROLE'
  | 'COACH_UNAVAILABLE'
  | 'EVENT_NOT_FOUND'
  | 'INVALID_DURATION'
  | 'DURATION_OUT_OF_RANGE'
  | 'CONFLICT_CHECK_ERROR'
  | 'TIME_SLOT_TAKEN'
  | 'UNAUTHORIZED'
  | 'USER_NOT_FOUND'
  | 'INVALID_SLUG'
  | 'SLUG_TAKEN'
  | 'RATE_LIMITED'
  | 'INVALID_INPUT'
  | 'INVALID_STATE'
  | 'AUTH_ERROR'
  | 'ITEM_NOT_FOUND'
  | 'INVALID_FILE_TYPE'
  | 'FILE_TOO_LARGE'
  | 'UPLOAD_FAILED'
  | 'MISSING_ORGANIZATION'
  | 'UNKNOWN_ERROR'
  | 'NO_SUBSCRIPTION'
  | 'NOT_MEMBER'
  | 'NO_SEATS_AVAILABLE'
  | 'LICENSE_EXISTS'
  | 'MISSING_USER'
  | 'MISSING_LICENSE'
  | 'LICENSE_NOT_FOUND'
  | 'ALREADY_REVOKED'
  | 'INVALID_OPERATION'
  | 'MISSING_TARGET_USER'
  | 'TARGET_NOT_MEMBER'
  | 'BUDGET_NOT_FOUND'
  | 'INVALID_AMOUNT'

export interface ApiError {
  code: ApiErrorCode;
  message: string;
  details?: unknown;
}

export interface ApiResponse<T> {
  data: T | null;
  error: ApiError | null;
} 