"use server"

import { createAuthClient } from '@/utils/auth'
import { withServerAction } from '@/utils/middleware/withServerAction'
import { ApiResponse } from '@/utils/types/api'
import { z } from 'zod'
import { 
  AdminMetrics, 
  AdminActivity, 
  SystemHealth, 
  SystemAlert, 
  UserAnalytics,
  DashboardData,
  AdminMetricsSchema,
  AdminActivitySchema,
  SystemHealthSchema,
  SystemAlertSchema,
  UserAnalyticsSchema,
  DashboardDataSchema,
  UpdateUserStatusSchema
} from '@/utils/types/admin'
import { revalidatePath } from 'next/cache'

const DEFAULT_ADMIN_METRICS: AdminMetrics = {
  ulid: '', // Will be generated by the database
  totalUsers: 0,
  activeUsers: 0,
  newUsers: 0,
  totalSessions: 0,
  completedSessions: 0,
  canceledSessions: 0,
  totalRevenue: 0,
  periodRevenue: 0,
  conversionRate: 0,
  retentionRate: 0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
}

// Actions
export const fetchDashboardData = withServerAction<DashboardData>(
  async (_, { userUlid, role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can access this endpoint'
          }
        }
      }

      const supabase = await createAuthClient()

      // Fetch system health
      const { data: healthData, error: healthError } = await supabase
        .from('SystemHealth')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(1)
        .single()

      if (healthError) {
        console.error('[DB_ERROR] SystemHealth:', healthError)
        throw healthError
      }

      // Fetch metrics
      const { data: metricsData, error: metricsError } = await supabase
        .from('AdminMetrics')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(1)
        .single()

      if (metricsError) {
        console.error('[DB_ERROR] AdminMetrics:', metricsError)
        throw metricsError
      }

      // Fetch recent activity
      const { data: activityData, error: activityError } = await supabase
        .from('AdminActivity')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(10)

      if (activityError) {
        console.error('[DB_ERROR] AdminActivity:', activityError)
        throw activityError
      }

      // Fetch system alerts
      const { data: alertsData, error: alertsError } = await supabase
        .from('SystemAlerts')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(10)

      if (alertsError) {
        console.error('[DB_ERROR] SystemAlerts:', alertsError)
        throw alertsError
      }

      // Validate data
      const validatedHealth = SystemHealthSchema.parse(healthData)
      const validatedMetrics = AdminMetricsSchema.parse(metricsData)
      const validatedActivity = z.array(AdminActivitySchema).parse(activityData)
      const validatedAlerts = z.array(SystemAlertSchema).parse(alertsData)

      const dashboardData: DashboardData = {
        systemHealth: validatedHealth,
        metrics: validatedMetrics,
        recentActivity: validatedActivity,
        systemAlerts: validatedAlerts
      }

      return { data: dashboardData, error: null }
    } catch (error) {
      console.error('[ADMIN_DASHBOARD_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
)

export const fetchAdminMetrics = withServerAction<AdminMetrics>(
  async (_, { userUlid, role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can access this endpoint'
          }
        }
      }

      const supabase = await createAuthClient()

      const { data, error } = await supabase
        .from('AdminMetrics')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(1)

      if (error?.code === 'PGRST116' || !data || data.length === 0) {
        return { data: DEFAULT_ADMIN_METRICS, error: null }
      }

      if (error) {
        console.error('[DB_ERROR] AdminMetrics:', error)
        throw error
      }

      const validatedMetrics = AdminMetricsSchema.parse(data[0])
      return { data: validatedMetrics, error: null }
    } catch (error) {
      console.error('[ADMIN_METRICS_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
)

export const updateUserStatus = withServerAction<{ success: boolean }>(
  async (input: { userUlid: string; status: 'active' | 'inactive' | 'suspended'; reason?: string }, { userUlid: adminUlid, role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can update user status'
          }
        }
      }

      // Validate input
      const validatedInput = UpdateUserStatusSchema.parse(input)

      const supabase = await createAuthClient()

      // Update user status
      const { error: updateError } = await supabase
        .from('User')
        .update({
          status: validatedInput.status,
          updatedAt: new Date().toISOString()
        })
        .eq('ulid', validatedInput.userUlid)

      if (updateError) throw updateError

      // Log the action
      const { error: logError } = await supabase
        .from('AdminActivity')
        .insert({
          ulid: '', // Will be generated by the database
          adminUlid,
          type: 'user_action',
          severity: 'info',
          description: `User status updated to ${validatedInput.status}${validatedInput.reason ? `: ${validatedInput.reason}` : ''}`,
          metadata: {
            userUlid: validatedInput.userUlid,
            status: validatedInput.status,
            reason: validatedInput.reason
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        })

      if (logError) throw logError

      revalidatePath('/dashboard/admin/user-mgmt')
      return { data: { success: true }, error: null }
    } catch (error) {
      console.error('[UPDATE_USER_STATUS_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
)

export const fetchUserAnalytics = withServerAction<UserAnalytics>(
  async (_, { userUlid, role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can access analytics'
          }
        }
      }

      const supabase = await createAuthClient()

      // Fetch user analytics
      const { data, error } = await supabase
        .from('UserAnalytics')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(1)
        .single()

      if (error) {
        console.error('[DB_ERROR] UserAnalytics:', error)
        throw error
      }

      const validatedAnalytics = UserAnalyticsSchema.parse(data)
      return { data: validatedAnalytics, error: null }
    } catch (error) {
      console.error('[USER_ANALYTICS_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
)

export const fetchAdminActivity = withServerAction<AdminActivity[]>(
  async (_, { userUlid, role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can access activity logs'
          }
        }
      }

      const supabase = await createAuthClient()

      const { data, error } = await supabase
        .from('AdminActivity')
        .select('*')
        .order('createdAt', { ascending: false })
        .limit(10)

      if (error) {
        console.error('[DB_ERROR] AdminActivity:', error)
        throw error
      }

      const validatedActivity = z.array(AdminActivitySchema).parse(data)
      return { data: validatedActivity, error: null }
    } catch (error) {
      console.error('[ADMIN_ACTIVITY_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
)

export const refreshDashboardData = withServerAction<void>(
  async (_, { role }) => {
    try {
      if (role !== 'ADMIN') {
        return {
          data: null,
          error: {
            code: 'FORBIDDEN',
            message: 'Only admins can refresh dashboard data'
          }
        }
      }

      revalidatePath('/dashboard/admin')
      return { data: undefined, error: null }
    } catch (error) {
      console.error('[REFRESH_DASHBOARD_ERROR]', error)
      return {
        data: null,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
          details: error instanceof Error ? { message: error.message } : undefined
        }
      }
    }
  }
) 